# Generated by Django 3.0.8 on 2020-07-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_pH', models.FloatField(default=0)),
                ('tds', models.IntegerField(default=0)),
                ('water_temp', models.FloatField(default=0)),
                ('air_temp', models.FloatField(default=0)),
                ('humidity', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Setting_name', models.CharField(max_length=25)),
                ('Value', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.CharField(max_length=40)),
                ('temperature', models.FloatField(default=0)),
                ('min_temperature', models.FloatField(default=0)),
                ('max_temperature', models.FloatField(default=0)),
                ('humidity', models.IntegerField(default=0)),
                ('weather_label', models.CharField(max_length=50)),
                ('weather_description', models.CharField(max_length=200)),
                ('cloudiness_level', models.IntegerField(default=0)),
                ('wind_speed', models.FloatField(default=0)),
            ],
        ),
    ]
